# PI=3.14
# r= float(input("enter redious: "))
# area_of_cercle = PI *r*r*r
# print(area_of_cercle)

# a = 17
# b = 100
# c = input
# if(a<b):
#  print('c the different:')

 




# number =[    
#     386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 
#     399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 
#     815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 
#     958,743, 527]
# for number in number:
#       if number == 237:
#           print(number)
#           break
#       elif number %2 ==0:
#           print(number)
#######################################################
# 1
# for i in range(1500,2700):
#     if(i%7==0 and i%5==0):
#         print(i)
#######################################################
# 2

# c/5 f-32/9 [ "where c = temperature in celsius and f = temperature in fahrenheit" ]
# f= float(input("enter your value:"))
# a= 5*(f-32)
# b= a/9
# print(b)
################################################################
# 3
# import random
# import  tkinter
# random_num = random.randrange(1,100)
# print(random_num)
# user_value = int(input('enter the value:'))
# if user_value==random_num:
#     print('you win')
# else: print(f'you lose, your correct ans is {random_num}')
##################################################################
# print(0)
# for i in range(0,6):
#     if (i%3==0):
#         continue
#     print(i)
#################################################################

# for i in range(1,6):
#   for j in range(1,i+1):
#       print('*',end='')
#   print()
###############################################################
# print('enter your number:')
# user_value=input('enter your input :')
# print(user_value) 

# for i in range('python'):
#     print[::-1]
#################################################


# x=[27,95,105,99]
# rem=[]
# for i in x:
#     remain=i%10
#     print(remain)
#     rem.append(remain)
# print(rem)
##########################################
# 4

# for i in range(1,6):
#   for j in range(1,i+1):
#       print('*',end='')
#   print()

# for k in range(-6,-1):
#      for a in range(1,k-1):
#           print("*",end="")
#      print("")

#####################################################
# 5
# i="python"
# a=()
# print(i[::-1])
# print i(a)
# user_in=int(input("enter value:"))
# print()
####################################
